/* generated using openapi-typescript-codegen -- do not edit */
/* istanbul ignore file */
/* tslint:disable */
/* eslint-disable */
import type { Barcode } from '../models/Barcode';
import type { BarcodeAssign } from '../models/BarcodeAssign';
import type { BarcodeGenerate } from '../models/BarcodeGenerate';
import type { BarcodePOAllocate } from '../models/BarcodePOAllocate';
import type { BarcodePOReceive } from '../models/BarcodePOReceive';
import type { BarcodeScanResult } from '../models/BarcodeScanResult';
import type { BarcodeSOAllocate } from '../models/BarcodeSOAllocate';
import type { BarcodeUnassign } from '../models/BarcodeUnassign';
import type { BulkRequest } from '../models/BulkRequest';
import type { PaginatedBarcodeScanResultList } from '../models/PaginatedBarcodeScanResultList';
import type { CancelablePromise } from '../core/CancelablePromise';
import { OpenAPI } from '../core/OpenAPI';
import { request as __request } from '../core/request';
export class BarcodeService {
    /**
     * Endpoint for handling generic barcode scan requests.
     *
     * Barcode data are decoded by the client application,
     * and sent to this endpoint (as a JSON object) for validation.
     *
     * A barcode could follow the internal InvenTree barcode format,
     * or it could match to a third-party barcode format (e.g. Digikey).
     * @param requestBody
     * @returns Barcode
     * @throws ApiError
     */
    public static barcodeCreate(
        requestBody: Barcode,
    ): CancelablePromise<Barcode> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/barcode/',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Endpoint for generating a barcode for a database object.
     *
     * The barcode is generated by the selected barcode plugin.
     * @param requestBody
     * @returns Barcode
     * @throws ApiError
     */
    public static barcodeGenerateCreate(
        requestBody: BarcodeGenerate,
    ): CancelablePromise<Barcode> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/barcode/generate/',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * List API endpoint for BarcodeScan objects.
     * @param limit Number of results to return per page.
     * @param offset The initial index from which to return the results.
     * @param ordering Which field to use when ordering the results.
     * @param result
     * @param search A search term. Searched fields: data.
     * @param user
     * @returns PaginatedBarcodeScanResultList
     * @throws ApiError
     */
    public static barcodeHistoryList(
        limit: number,
        offset?: number,
        ordering?: 'user' | '-user' | 'timestamp' | '-timestamp' | 'endpoint' | '-endpoint' | 'result' | '-result',
        result?: boolean,
        search?: string,
        user?: number,
    ): CancelablePromise<PaginatedBarcodeScanResultList> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/barcode/history/',
            query: {
                'limit': limit,
                'offset': offset,
                'ordering': ordering,
                'result': result,
                'search': search,
                'user': user,
            },
        });
    }
    /**
     * Perform a DELETE operation against this list endpoint.
     *
     * Note that the typical DRF list endpoint does not support DELETE,
     * so this method is provided as a custom implementation.
     * @param requestBody
     * @returns void
     * @throws ApiError
     */
    public static barcodeHistoryBulkDestroy(
        requestBody: BulkRequest,
    ): CancelablePromise<void> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/barcode/history/',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Detail endpoint for a BarcodeScan object.
     * @param id
     * @returns BarcodeScanResult
     * @throws ApiError
     */
    public static barcodeHistoryRetrieve(
        id: number,
    ): CancelablePromise<BarcodeScanResult> {
        return __request(OpenAPI, {
            method: 'GET',
            url: '/api/barcode/history/{id}/',
            path: {
                'id': id,
            },
        });
    }
    /**
     * Detail endpoint for a BarcodeScan object.
     * @param id
     * @returns void
     * @throws ApiError
     */
    public static barcodeHistoryDestroy(
        id: number,
    ): CancelablePromise<void> {
        return __request(OpenAPI, {
            method: 'DELETE',
            url: '/api/barcode/history/{id}/',
            path: {
                'id': id,
            },
        });
    }
    /**
     * Endpoint for assigning a barcode to a stock item.
     *
     * - This only works if the barcode is not already associated with an object in the database
     * - If the barcode does not match an object, then the barcode hash is assigned to the StockItem
     * @param requestBody
     * @returns BarcodeAssign
     * @throws ApiError
     */
    public static barcodeLinkCreate(
        requestBody: BarcodeAssign,
    ): CancelablePromise<BarcodeAssign> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/barcode/link/',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Endpoint for allocating parts to a purchase order by scanning their barcode.
     *
     * Note that the scanned barcode may point to:
     *
     * - A Part object
     * - A ManufacturerPart object
     * - A SupplierPart object
     * @param requestBody
     * @returns BarcodePOAllocate
     * @throws ApiError
     */
    public static barcodePoAllocateCreate(
        requestBody: BarcodePOAllocate,
    ): CancelablePromise<BarcodePOAllocate> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/barcode/po-allocate/',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Endpoint for handling receiving parts by scanning their barcode.
     *
     * Barcode data are decoded by the client application,
     * and sent to this endpoint (as a JSON object) for validation.
     *
     * The barcode should follow a third-party barcode format (e.g. Digikey)
     * and ideally contain order_number and quantity information.
     *
     * The following parameters are available:
     *
     * - barcode: The raw barcode data (required)
     * - purchase_order: The purchase order containing the item to receive (optional)
     * - location: The destination location for the received item (optional)
     * @param requestBody
     * @returns BarcodePOReceive
     * @throws ApiError
     */
    public static barcodePoReceiveCreate(
        requestBody: BarcodePOReceive,
    ): CancelablePromise<BarcodePOReceive> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/barcode/po-receive/',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Endpoint for allocating stock to a sales order, by scanning barcode.
     *
     * The scanned barcode should map to a StockItem object.
     *
     * Additional fields can be passed to the endpoint:
     *
     * - SalesOrder (Required)
     * - Line Item
     * - Shipment
     * - Quantity
     * @param requestBody
     * @returns BarcodeSOAllocate
     * @throws ApiError
     */
    public static barcodeSoAllocateCreate(
        requestBody: BarcodeSOAllocate,
    ): CancelablePromise<BarcodeSOAllocate> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/barcode/so-allocate/',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
    /**
     * Endpoint for unlinking / unassigning a custom barcode from a database object.
     * @param requestBody
     * @returns BarcodeUnassign
     * @throws ApiError
     */
    public static barcodeUnlinkCreate(
        requestBody?: BarcodeUnassign,
    ): CancelablePromise<BarcodeUnassign> {
        return __request(OpenAPI, {
            method: 'POST',
            url: '/api/barcode/unlink/',
            body: requestBody,
            mediaType: 'application/json',
        });
    }
}
